name: imgur
description: A high-level Imgur API Client Library that uses Imgur's v3 API.
version: 1.1.1
homepage: https://github.com/shellbear/imgur.dart
repository: https://github.com/shellbear/imgur.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http:
  json_annotation:

dev_dependencies:
  build_runner: ^1.7.1
  json_serializable: ^3.2.3
  pedantic: ^1.8.0
  test: ^1.6.0
